apiVersion: v1
kind: Service
metadata:
  name: myfastapi-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: myfastapi
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: myfastapi
  sessionAffinity: None
